# Generated by Django 6.0.2 on 2026-02-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
