# Generated by Django 6.0.2 on 2026-02-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_category_options_alter_category_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=255, unique=True),
        ),
    ]
