# Generated by Django 6.0.2 on 2026-03-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_menuitem_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='menu_items',
            new_name='image',
        ),
    ]
