# Generated by Django 6.0.2 on 2026-03-04 17:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_rename_menu_items_menuitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='images',
        ),
        migrations.AddField(
            model_name='category',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
