# Generated by Django 6.0.2 on 2026-03-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_category_images_category_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='percentage_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
