# Generated by Django 6.0.2 on 2026-03-15 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_menuitem_percentage_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='base_price',
            new_name='price',
        ),
    ]
