# Generated by Django 6.0.2 on 2026-02-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiRequestLogger',
        ),
    ]
