# Generated by Django 6.0.2 on 2026-04-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
